#!/usr/bin/env python3
"""Build compact SVG path data from the Japan prefecture GeoJSON."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

PROJECTIONS = {
    "main": {
        "bounds": (128.0, 146.5, 30.0, 46.0),
        "frame": (165.0, 20.0, 570.0, 570.0),
    },
    "southwest": {
        "bounds": (122.5, 131.0, 23.5, 30.0),
        "frame": (20.0, 465.0, 145.0, 125.0),
    },
    "pacific": {
        "bounds": (136.0, 154.0, 20.0, 30.0),
        "frame": (20.0, 55.0, 145.0, 90.0),
    },
}


def projection_name(latitude: float, longitude: float) -> str:
    if latitude < 30.0 and longitude < 133.0:
        return "southwest"
    if latitude < 30.0 or longitude > 146.5:
        return "pacific"
    return "main"


def project(latitude: float, longitude: float, name: str) -> tuple[float, float]:
    min_lng, max_lng, min_lat, max_lat = PROJECTIONS[name]["bounds"]
    x, y, width, height = PROJECTIONS[name]["frame"]
    projected_x = x + ((longitude - min_lng) / (max_lng - min_lng)) * width
    projected_y = y + ((max_lat - latitude) / (max_lat - min_lat)) * height
    return projected_x, projected_y


def point_line_distance(
    point: tuple[float, float],
    start: tuple[float, float],
    end: tuple[float, float],
) -> float:
    if start == end:
        return ((point[0] - start[0]) ** 2 + (point[1] - start[1]) ** 2) ** 0.5

    dx = end[0] - start[0]
    dy = end[1] - start[1]
    amount = ((point[0] - start[0]) * dx + (point[1] - start[1]) * dy) / (
        dx * dx + dy * dy
    )
    amount = max(0.0, min(1.0, amount))
    nearest = (start[0] + amount * dx, start[1] + amount * dy)
    return ((point[0] - nearest[0]) ** 2 + (point[1] - nearest[1]) ** 2) ** 0.5


def simplify(
    points: list[tuple[float, float]], tolerance: float
) -> list[tuple[float, float]]:
    if len(points) <= 2:
        return points

    furthest_distance = 0.0
    furthest_index = 0
    for index in range(1, len(points) - 1):
        distance = point_line_distance(points[index], points[0], points[-1])
        if distance > furthest_distance:
            furthest_distance = distance
            furthest_index = index

    if furthest_distance <= tolerance:
        return [points[0], points[-1]]

    left = simplify(points[: furthest_index + 1], tolerance)
    right = simplify(points[furthest_index:], tolerance)
    return left[:-1] + right


def ring_path(coordinates: list[list[float]], tolerance: float) -> str:
    longitudes = [point[0] for point in coordinates]
    latitudes = [point[1] for point in coordinates]
    center_lng = (min(longitudes) + max(longitudes)) / 2
    center_lat = (min(latitudes) + max(latitudes)) / 2
    name = projection_name(center_lat, center_lng)

    projected = [project(point[1], point[0], name) for point in coordinates]
    if projected[0] == projected[-1]:
        projected.pop()
    if len(projected) < 3:
        return ""

    projected.append(projected[0])
    reduced = simplify(projected, tolerance)
    if len(reduced) < 4:
        return ""

    commands = [f"M{reduced[0][0]:.1f},{reduced[0][1]:.1f}"]
    commands.extend(f"L{x:.1f},{y:.1f}" for x, y in reduced[1:-1])
    commands.append("Z")
    return "".join(commands)


def feature_path(feature: dict, tolerance: float) -> str:
    geometry = feature["geometry"]
    polygons = (
        geometry["coordinates"]
        if geometry["type"] == "MultiPolygon"
        else [geometry["coordinates"]]
    )
    paths = []
    for polygon in polygons:
        for ring in polygon:
            path = ring_path(ring, tolerance)
            if path:
                paths.append(path)
    return "".join(paths)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--tolerance", type=float, default=0.04)
    args = parser.parse_args()

    source = json.loads(args.source.read_text(encoding="utf-8"))
    prefectures = []
    for feature in sorted(source["features"], key=lambda item: item["properties"]["id"]):
        prefectures.append(
            {
                "id": feature["properties"]["id"],
                "name": feature["properties"]["nam_ja"],
                "path": feature_path(feature, args.tolerance),
            }
        )

    payload = json.dumps(prefectures, ensure_ascii=False, separators=(",", ":"))
    args.output.write_text(
        "// Generated by scripts/build_japan_map.py\n"
        f"window.JAPAN_PREFECTURE_PATHS={payload};\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
